import React from "react";

function MainContent(){
  var MainContentStyles = {
    listStyle: "none",
  }
  return (
  <div style={MainContentStyles}>
    <p>It all began about ten years ago. I had reached a considerably more relaxed period in my life – a time when I had come to feel that there was more to living than science, a time of awakening of my social consciousness and amiability, a time when I was open to new experiences. I had become friendly with a group of people who occasionally smoked cannabis, irregularly, but with evident pleasure. Initially I was unwilling to partake, but the apparent euphoria that cannabis produced and the fact that there was no physiological addiction to the plant eventually persuaded me to try. My initial experiences were entirely disappointing; there was no effect at all, and I began to entertain a variety of hypotheses about cannabis being a placebo which worked by expectation and hyperventilation rather than by chemistry. After about five or six unsuccessful attempts, however, it happened.

I was lying on my back in a friend’s living room idly examining the pattern of shadows on the ceiling cast by a potted plant (not cannabis!). I suddenly realized that I was examining an intricately detailed miniature Volkswagen, distinctly outlined by the shadows. I was very skeptical at this perception, and tried to find inconsistencies between Volkswagens and what I viewed on the ceiling. But it was all there, down to hubcaps, license plate, chrome, and even the small handle used for opening the trunk. When I closed my eyes, I was stunned to find that there was a movie going on the inside of my eyelids. Flash . . . a simple country scene with red farmhouse, a blue sky, white clouds, yellow path meandering over green hills to the horizon. . . Flash . . . same scene, orange house, brown sky, red clouds, yellow path, violet fields . . . Flash . . . Flash . . . Flash. The flashes came about once a heartbeat. Each flash brought the same simple scene into view, but each time with a different set of colors . . . exquisitely deep hues, and astonishingly harmonious in their juxtaposition. Since then I have smoked occasionally and enjoyed it thoroughly. It amplifies torpid sensibilities and produces what to me are even more interesting effects, as I will explain shortly.

I can remember another early visual experience with cannabis, in which I viewed a candle flame and discovered in the heart of the flame, standing with magnificent indifference, the black-hatted and -cloaked Spanish gentleman who appears on the label of the Sandeman sherry bottle. Looking at fires when high, by the way, especially through one of those prism kaleidoscopes which image their surroundings, is an extraordinarily moving and beautiful experience.

I want to explain that at no time did I think these things ‘really’ were out there. I knew there was no Volkswagen on the ceiling and there was no Sandeman salamander man in the flame. I don’t feel any contradiction in these experiences. There’s a part of me making, creating the perceptions which in everyday life would be bizarre; there’s another part of me which is a kind of observer. About half of the pleasure comes from the observer-part appreciating the work of the creator-part. I smile, or sometimes even laugh out loud at the pictures on the insides of my eyelids. In this sense, I suppose cannabis is psychotomimetic, but I find none of the panic or terror that accompanies some psychoses. Possibly this is because I know it’s my own trip, and that I can come down rapidly any time I want to.

While my early perceptions were all visual, and curiously lacking in images of human beings, both of these items have changed over the intervening years. I find that today a single joint is enough to get me high. I test whether I’m high by closing my eyes and looking for the flashes. They come long before there are any alterations in my visual or other perceptions. I would guess this is a signal-to-noise problem, the visual noise level being very low with my eyes closed. Another interesting information-theoretical aspects is the prevalence – at least in my flashed images – of cartoons: just the outlines of figures, caricatures, not photographs. I think this is simply a matter of information compression; it would be impossible to grasp the total content of an image with the information content of an ordinary photograph, say 108 bits, in the fraction of a second which a flash occupies. And the flash experience is designed, if I may use that word, for instant appreciation. The artist and viewer are one. This is not to say that the images are not marvelously detailed and complex. I recently had an image in which two people were talking, and the words they were saying would form and disappear in yellow above their heads, at about a sentence per heartbeat. In this way it was possible to follow the conversation. At the same time an occasional word would appear in red letters among the yellows above their heads, perfectly in context with the conversation; but if one remembered these red words, they would enunciate a quite different set of statements, penetratingly critical of the conversation. The entire image set which I’ve outlined here, with I would say at least 100 yellow words and something like 10 red words, occurred in something under a minute.</p>
  </div>
  );
}
//
// SideBar.propTypes = {
//   links: PropTypes.string.isRequired,
// };

export default MainContent;
